# Generated by Django 2.2 on 2020-03-28 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idm', models.CharField(max_length=9)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 14, 44, 1, 568583))),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 14, 44, 1, 568583))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=50)),
            ],
        ),
    ]
