# Generated by Django 2.2 on 2020-03-28 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 16, 29, 8, 892753)),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 16, 29, 8, 892753)),
        ),
    ]
