# Generated by Django 2.2 on 2020-03-28 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0006_auto_20200328_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 17, 16, 1, 934071)),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 17, 16, 1, 934071)),
        ),
    ]
